title: Detecting temperature with the Sense HAT
hero_image: images/banner.png
description: Take a temperature reading with the Sense HAT
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
ingredient: true
listed: false
copyedit: false
interests: 
technologies: "python, sense hat"
steps:
  - title: Detecting temperature
